\input texinfo

@setfilename libpac.info
@settitle libpac Manual

@titlepage
@title libpac Manual
@author Thomas Pfaff @email{thomaspfaff@users.sourceforge.net}
@end titlepage

@c @contents
@ifnottex
@node Top
@top libpac
@end ifnottex

This manual documents how to use libpac and how to report bugs.  It corresponds
to libpac version 0.9.0.

@menu
* Overview::            Overview.
* API::                 libpac API.
* Bugs::                Reporting bugs.
* Function Index::	Function index.
@end menu

@node Overview
@chapter Overview
@include overview.texinfo

@node API
@chapter API
@include api.texinfo

@node Bugs
@chapter Bugs
@include bugs.texinfo

@node Function Index
@unnumbered Function Index
@printindex fn

@bye
